- name: Install Certification Authority feature
  win_feature:
    name: Adcs-Cert-Authority
    include_management_tools: yes

- name: setup Certification Authority
  win_shell: Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -Force
  args:
    creates: C:\Windows\System32\CertSrv\CertEnroll
  register: cert_authority

- name: Reboot to finish configuring Certification Authority
  win_reboot:
    test_command: 'Get-ADUser -Filter {Name -eq "Administrator"}'
  when: cert_authority is changed