---
# tasks file for win-ad-forest
- name: Push script to Windows machine
  win_template:
    src: Install-ADDSForest.ps1.j2
    dest: 'C:\Windows\Temp\Install-ADDSForest.ps1'

- name: Promote to Forest Domain controller
  win_shell: 'C:\Windows\Temp\Install-ADDSForest.ps1'
  register: result
  failed_when: '"Success" not in result.stdout or "Failed" in result.stdout or "Error" in result.stdout'

- name: Restart
  win_reboot:
    test_command: 'dsquery user -name Administrator'
