---
# tasks file for win-ad-common

- wait_for_connection:

- name: set host name from ansible inventory name
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname

- name: Reboot
  win_reboot:
  when: hostname.reboot_required

- setup:
  when: hostname is changed

- name: Turn off firewall
  win_shell: |
    Get-NetFirewallProfile | Set-NetFirewallProfile -Enabled False

- name: install sshd
  include_role: name=windows/sshd

- name: Enforce AES encryption
  win_security_policy:
    section: Registry Values
    key: "MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Kerberos\\Parameters\\SupportedEncryptionTypes"
    value: 4,2147483644
