ad_admin_name: Administrator
ad_admin_password: Secret123
admin_name: admin
admin_password: Secret.123
debug: false
dirman_dn: cn=Directory Manager
dirman_password: Secret.123
dns_forwarder: {{ dns_server.stdout }}
domains:
- hosts:
{% for host in groups['all'] %}
{% if host.startswith('master') or host.startswith('replica') or host.startswith('client') %}
    - external_hostname: {{ hostvars[host]['inventory_hostname'] }}.ipa.test
      name: {{ hostvars[host]['inventory_hostname'] }}.ipa.test
      ip: {{ hostvars[host]['ansible_default_ipv4']['address'] }}
{% if host.startswith('master') %}
      role: master
{% endif %}
{% if host.startswith('replica') %}
      role: replica
{% endif %}
{% if host.startswith('client') %}
      role: client
{% endif %}
{% endif %}
{% endfor %}
  name: ipa.test
  type: IPA

{% if 'ad-root' in groups['all'] %}
- name: ad.test
  type: AD
  hosts:
    - external_hostname: ad-root.ad.test
      ip: {{ hostvars['ad-root']['ansible_ip_addresses']|ipv4|first }}
      name: ad-root.ad.test
      role: ad
      username: Administrator
      password: Secret123
{% endif %}

{% if 'ad-child' in groups['all'] %}
- name: child.ad.test
  type: AD_SUBDOMAIN
  hosts:
    - external_hostname: ad-child.child.ad.test
      ip: {{ hostvars['ad-child']['ansible_ip_addresses']|ipv4|first }}
      name: ad-child.child.ad.test
      role: ad_subdomain
      username: Administrator
      password: Secret123
{% endif %}

{% if 'ad-tree' in groups['all'] %}
- name: adtree.test
  type: AD_TREEDOMAIN
  hosts:
    - external_hostname: ad-tree.adtree.test
      ip: {{ hostvars['ad-tree']['ansible_ip_addresses']|ipv4|first }}
      name: ad-tree.adtree.test
      role: ad_treedomain
      username: Administrator
      password: Secret123
{% endif %}

nis_domain: ipatest
ntp_server: 1.pool.ntp.org
root_ssh_key_filename: /root/.ssh/freeipa_pr_ci_insecure
test_dir: /ipatests
