---
# # Update Administrator's password
- hosts: ad-root,ad-child,ad-tree
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: set administrator password
      changed_when: yes
      ignore_errors: yes
      win_user:
        name: Administrator
        password: Secret123

- hosts: ad-root,ad-child,ad-tree
  any_errors_fatal: true
  vars:
    ansible_user: Administrator
    ansible_password: Secret123
  roles:
    - windows/common

- name: setup AD root domain
  hosts: ad-root
  any_errors_fatal: true
  vars:
    ansible_user: Administrator
    ansible_password: Secret123
  roles:
    - windows/ad-root

- name: setup AD child domains
  hosts: ad-child,ad-tree
  any_errors_fatal: true
  vars:
    ansible_user: Administrator
    ansible_password: Secret123
    role: "{{ inventory_hostname }}"
  tasks:
    - include_role:
        name: "windows/{{ role }}"

- name: create test data in AD domains
  hosts: ad-root,ad-child,ad-tree
  any_errors_fatal: true
  vars:
    ansible_user: Administrator
    ansible_password: Secret123
    role: "{{ inventory_hostname }}"
  tasks:
  - include_role:
      name: windows/ipa-ad-data
      tasks_from: "{{ role }}"

# Provision linux hosts but include ad and ad-child in the list so we can access
# their data to generate ipa test config file
- hosts: all
  gather_facts: yes
  roles:
    - role: machine/provision
      when: not inventory_hostname.startswith('ad')
