---
# # Update Administrator's password
- hosts: ad-root,ad-child,ad-tree
  gather_facts: no
  tasks:
    - name: set administrator password
      changed_when: yes
      ignore_errors: yes
      win_user:
        name: Administrator
        password: Secret123

- hosts: ad-root,ad-child,ad-tree
  vars:
    ansible_user: Administrator
    ansible_password: Secret123
    role: "{{ inventory_hostname }}"
  tasks:
    - include_role: name=windows/common
    - include_role:
        name: "windows/{{ role }}"
    - include_role:
        name: windows/ipa-ad-data
        tasks_from: "{{ role }}"

# Provision linux hosts but include ad and ad-child in the list so we can access
# their data to generate ipa test config file
- hosts: all
  gather_facts: yes
  roles:
    - role: machine/provision
      when: not inventory_hostname.startswith('ad')
